### ISSUE TITLE
Blog description lsp root

### ISSUE THREAD

**Issue by enikko** [elizagamedev/unity.el#11]
I know this issue is not really a part of the GitHub repo per se. However, I couldn't find a way to leave a comment on your blog entry describing how to set up Emacs for unity.

Anyhow, I got quite stuck on when trying to set everything up because lsp-mode auto-guessed the root folder wrongly. Essentially, I had to manually set it to the root of the unity project to get it working (unfortunately not using git as version control for my project). It would be very nice if this was added to the instructions. Otherwise, lovely instructions to get everything up and running. Thanks a lot for sharing it.

**Comment by elizagamedev** [comment]
Hi, thank you for your feedback! (The blog is hosted on github static pages, actually; I ought to link to the [issues page](https://github.com/elizagamedev/elizagamedev.github.io/issues) in the blog as a sort of "comments" section)

I've been meaning to do a part 2 of that article with some of the new (and frustratedly exciting) issues I've continued to encounter with unsupported editors in Unity, and I'll be sure to include this tip in the post when I get around to it.

**Comment by elizagamedev** [comment]
Made a new post! https://eliza.sh/2022-07-31-using-unity-editor-with-emacs-(part-2).html

**Comment by enikko** [comment]
Looks nice, just one comment: I’m quite sure that the reason lsp-mode doesn’t find the project root is that it doesn’t recognise plastic scam version control. I say quite sure because more or less the first thing I usually do is to set up the appropriate version (usually git but to my knowledge, unity uses quite a lot of binary files which makes git less preferable when it lacks locking). However, in this case I’m not 100% sure because I played around with a few version control systems before deciding to try plastic scm for this project.

Anyhow, point is that it might be worth mentioning that plastic scm might not be recognised as a project root.
