### ISSUE TITLE
Emacs Not Launching

### ISSUE THREAD

**Issue by williamJmelton** [elizagamedev/unity.el#2]
Followed the install instructions to the letter:
1. Added the package using straight.el to my doom emacs config
2. ran doom sync
3. generated the shim
4. pointed my external editor to the dummy code executable

when clicking the script file nothing happens....any way I can check a log or anything?

**Comment by Dash-L** [comment]
I had a similar problem using emacsclient. I don't know much about emacs/emacsclient, so I'm not really sure why this worked, but I changed `emacsclient -n +$(Line):$(Column) $(File)` to `emacsclient --create-frame +$(Line):$(Column) $(File)` for the External Script Editor Args.

**Comment by kevzettler** [comment]
Have unity pointed to the `code.app` shim on MacOs 12.3.1 nothing happening. If I try execution `code.app` manually nothing happens either. Any way to debug? 

hmm if I manually invoke the shim from terminal with: `/Applications/code.app emacsclient -n ~/.emacs.d/init.el`  opens a buffer in emacs

**Comment by elizagamedev** [comment]
I'm going to close this issue but please reopen it if neither of those options were able to fix it for you.
