### ISSUE TITLE
`.csproj` and `.sln` are created but  `type or namespace name 'UnityEngine' could not be found` from lsp

### ISSUE THREAD

**Issue by Piturnah** [elizagamedev/unity.el#6]
`.csproj` and `.sln` are created but  `type or namespace name 'UnityEngine' could not be found` from lsp

This is after following the guide [here](https://eliza.sh/2021-06-01-using-unity-editor-with-emacs.html)
lsp is otherwise working correctly with omnisharp.

**Additional context**
OS: Debian GNU/Linux 11
Unity Version: 2020.3.30f1

**Comment by Piturnah** [comment]
My apologies, just realised this duplicates #5. I will investigate this solution and close if necessary.

**Comment by Piturnah** [comment]
Updating the root for lsp did not resolve the issue.

**Comment by elizagamedev** [comment]
Unfortunately it's difficult for me to help with issues like these. unity.el is really only limited to being able to:

1. Help unity generate sln/csproj files, which it looks like was able to work for you.
2. Keep meta files with their corresponding owners.

Issues with LSP are better discussed on the LSP issue trackers.
