### ISSUE TITLE
What path to put emacsclient at?

### ISSUE THREAD

**Issue by kevzettler** [elizagamedev/unity.el#7]
Hi @elizagamedev thanks for your work on this project. What path do you have `emacsclient` at. I suspect my `code.app` shim or Unity itself doesn't have access as they may be in a different path or env than where my `emacsclient` is

**Comment by elizagamedev** [comment]
On macOS unity is probably not inheriting your bash PATH when running the shim. The simplest solution would be to change emacsclient to an absolute path.

**Comment by kevzettler** [comment]
@elizagamedev that was indeed the issue and it works as expected now with an absolute path. I also suspect this was maybe what the user at #2 was seeing. I opened a PR to add a note to the readme. #8 Thanks for the help!
